In [ ]:
import numpy as np

In [ ]:


a = [6, 8, 2, 10]
b = [3, 7, 9, 1]
ab = []

for i in range(0, len(a)):
    ab.append(a[i] * b[i])

print(ab)

a = np.array([6, 8, 2, 10])
b = np.array([3, 7, 9, 1])

result = a * b
print(result)

[18, 56, 18, 10]
[18 56 18 10]


Numpy Arrayi Oluşturma

In [ ]:
liste = [1, 2, 3, 4, 5]

np_arr = np.array(liste)
type(np_arr)

np_zeros = np.zeros(10, dtype=int)
print(np_zeros)

np_rand = np.random.randint(0, 10, size=10)
print(np_rand)

np_matrix = np.random.normal(10, 4, (3, 4))
print(np_matrix)

[0 0 0 0 0 0 0 0 0 0]
[4 8 2 2 4 1 9 0 7 4]
[[ 7.04190644  5.31007543 13.10327133 12.30753018]
 [ 4.64781009  8.42824452  7.62290081  3.75273553]
 [ 6.28391115  5.65251183  9.75937108  7.14755699]]


In [ ]:
# ndim: boyut sayis1
# shape: boyut bilgisi
# size: toplam eleman sayis1
# dtype: array veri tipi

a = np.random.normal(12, 4, (5, 2))
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[[17.8328217   9.4863729 ]
 [10.34259483  3.838807  ]
 [10.1013822   8.754135  ]
 [10.09435977 10.33179196]
 [11.46523016  5.95093207]]
2
(5, 2)
10
float64


In [ ]:
ar = np.random.randint(1, 10, size=12)
ar
ar.reshape(2, 6)

array([[2, 5, 5, 1, 3, 1],
       [1, 2, 9, 2, 7, 4]])

In [ ]:
m = np.random.randint(-3, 19, size=(3, 5))
print(m)
m[0, 0] = 2.9
m[0, 0]
m[:, 0]
m[1, :]
m[0:2, 0:3]


[[10 15 16 -3 10]
 [ 6 17 16  5  3]
 [12  8 17  8 -2]]


array([[ 2, 15, 16],
       [ 6, 17, 16]])

Fancy Index Kavramı

In [ ]:
v = np.arange(0, 48, 8)
print(v)
catch = [1, 2, 4]
v[catch]

[ 0  8 16 24 32 40]


array([ 8, 16, 32])

Koşullu İşlemler

In [ ]:
#normal
v = np.array([1, 4, 9, 16, 25])
ab = []
for i in v:
    if i < 9:
        ab.append(i)
print(ab)
#numpy ile
v < 9
print(v[v < 9])
v[v != 9]
v[v == 9]
v[v >= 9]

[1, 4]
[1 4]


array([ 9, 16, 25])

Matematiksel İşlemler

In [ ]:
import numpy as np

v = np.array([1, 2, 3, 4, 5])
v / 5

v * 5 / 10
v ** 2
v - 1

np.subtract(v, 7)
np.add(v, 1)
np.mean(v)
np.sum(v)
np.min(v)
np.max(v)
np.var(v)

array([-6, -5, -4, -3, -2])